---

services:
  elasticsearch:
    enabled: false
    version: latest
    ram: 2048M
    service_name: ElasticSearch
    service_url: https://{}
  kibana:
    enabled: false
    version: latest
    ram: 2048M
    service_name: Kibana
    service_url: https://{}
  logstash:
    enabled: false
    version: latest
    ram: 2048M
    service_name: Logstash
    service_url: https://{}
