version: '2.2'

services:
    logstash:
        image: docker.elastic.co/logstash/logstash:${DOCKER_LOGSTASH_VERSION}
        mem_limit: ${DOCKER_LOGSTASH_RAM}
        container_name: ${COMPOSE_PROJECT_NAME}_logstash
        hostname: ${COMPOSE_PROJECT_NAME}_logstash
        networks: [stakkr]
        volumes:
            - ${COMPOSE_BASE_DIR}/data/logstash:/usr/share/logstash/pipeline
        environment:
            server_name: logstash
            elasticsearch_url: ${COMPOSE_PROJECT_NAME}_elasticsearch
        labels:
            - traefik.frontend.rule=Host:logstash.${COMPOSE_PROJECT_NAME}.${PROXY_DOMAIN}
            - traefik.port=9600
